openapi: 3.0.0
info:
  title: skotune-ai BFF
  version: 1.0.0
paths:
  /api/bff:
    get:
      summary: B000_000_共通機能_ヘルスチェックBFF
      description: BFFサーバーが正常に稼働しているか確認
      responses:
        "200":
          description: 成功時のレスポンス
    post:
      summary: BFF統合エンドポイント
      description: |
        ifIdにより実行する処理を切り替え
        payloadの内容は各IFによって異なる
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/B000_001_Request_Get"
                - $ref: "#/components/schemas/B000_002_Request_Get"
                - $ref: "#/components/schemas/B001_001_Request_Post"
                - $ref: "#/components/schemas/B001_002_Request_Get"
                - $ref: "#/components/schemas/B001_002_Request_Delete"
                - $ref: "#/components/schemas/B003_001_Request_Get"
                - $ref: "#/components/schemas/B003_002_Request_Get"
                - $ref: "#/components/schemas/B004_001_Request_Get"
                - $ref: "#/components/schemas/B004_001_Request_Post"
                - $ref: "#/components/schemas/B004_001_Request_Delete"
                - $ref: "#/components/schemas/B004_002_Request_Get"
                - $ref: "#/components/schemas/B004_002_Request_Post"
                - $ref: "#/components/schemas/B004_002_Request_Put"
                - $ref: "#/components/schemas/B004_002_Request_Delete"
            examples:
              B000_001_GET:
                summary: B000_001_共通機能_メニュー情報BFF_リクエスト（GET）
                value:
                  ifId: B000_001
                  method: get
                  payload:
                    administrator_flg: true
              B000_002_GET:
                summary: B000_002_共通機能_コード値情報BFF_リクエスト（GET）
                value:
                  ifId: B000_002
                  method: get
                  payload:
                    code_id: "0001"
              B001_001_POST:
                summary: B001_001_認証機能_ログイン照会BFF_リクエスト（POST）
                value:
                  ifId: B001_001
                  method: post
                  payload:
                    user_id: "test@gmail.com"
                    password: "test"
              B001_002_GET:
                summary: B001_002_認証機能_トークン情報BFF_リクエスト（GET）
                value:
                  ifId: B001_002
                  method: get
              B001_002_DELETE:
                summary: B001_002_認証機能_トークン情報BFF_リクエスト（DELETE）
                value:
                  ifId: B001_002
                  method: delete
              B003_001_GET:
                summary: B003_001_検索機能_楽曲情報BFF_リクエスト（GET）
                value:
                  ifId: B003_001
                  method: get
                  payload:
                    artist_name: "YOASOBI"
                    tune_name: "アイドル"
              B003_002_GET:
                summary: B003_002_検索機能_全楽曲情報BFF_リクエスト（GET）
                value:
                  ifId: B003_002
                  method: get
                  payload:
                    artist_id: "64tJ2EAv1R6UaZqc4iOCyj"
              B004_001_GET:
                summary: B004_001_採点機能_楽曲予約情報BFF_リクエスト（GET）
                value:
                  ifId: B004_001
                  method: get
                  payload:
                    user_id: "test@gmail.com"
              B004_001_POST:
                summary: B004_001_採点機能_楽曲予約情報BFF_リクエスト（POST）
                value:
                  ifId: B004_001
                  method: post
                  payload:
                    user_id: "test@gmail.com"
                    artist_id: "64tJ2EAv1R6UaZqc4iOCyj"
                    artist_name: "YOASOBI"
                    tune_id: "7ovUcF5uHTBRzUpB6ZOmvt"
                    tune_name: "アイドル"
                    model_type: "10"
                    score: 88.888
                    scoring_date: "2025-10-01"
              B004_001_DELETE:
                summary: B004_001_採点機能_楽曲予約情報BFF_リクエスト（DELETE）
                value:
                  ifId: B004_001
                  method: delete
                  payload:
                    user_id: "test@gmail.com"
                    tune_id: "7ovUcF5uHTBRzUpB6ZOmvt"
              B004_002_GET:
                summary: B004_002_採点機能_採点履歴情報BFF_リクエスト（GET）
                value:
                  ifId: B004_002
                  method: get
                  payload:
                    user_id: "test@gmail.com"
                    from_date: "2025-10-01"
                    to_date: "2025-10-31"
              B004_002_POST:
                summary: B004_002_採点機能_採点履歴情報BFF_リクエスト（POST）
                value:
                  ifId: B004_002
                  method: post
                  payload:
                    user_id: "test@gmail.com"
                    artist_id: "64tJ2EAv1R6UaZqc4iOCyj"
                    artist_name: "YOASOBI"
                    tune_id: "7ovUcF5uHTBRzUpB6ZOmvt"
                    tune_name: "アイドル"
                    model_type: "10"
                    score: 88.888
                    scoring_date: "2025-10-01"
              B004_002_PUT:
                summary: B004_002_採点機能_採点履歴情報BFF_リクエスト（PUT）
                value:
                  ifId: B004_002
                  method: put
                  payload:
                    user_id: "test@gmail.com"
                    tune_id: "7ovUcF5uHTBRzUpB6ZOmvt"
                    tune_name: "アイドル"
                    model_type: "01"
                    score: 88.888
                    scoring_date: "2025-10-13"
                    registered_model_type: "10"
                    registered_scoring_date: "2025-10-01"
              B004_002_DELETE:
                summary: B004_002_採点機能_採点履歴情報BFF_リクエスト（DELETE）
                value:
                  ifId: B004_002
                  method: delete
                  payload:
                    user_id: "test@gmail.com"
                    tune_id: "7ovUcF5uHTBRzUpB6ZOmvt"
                    model_type: "10"
                    scoring_date: "2025-10-01"
      responses:
        "200":
          description: 正常応答
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/B000_001_Response_Get"
                  - $ref: "#/components/schemas/B000_002_Response_Get"
                  - $ref: "#/components/schemas/B001_001_Response_Post"
                  - $ref: "#/components/schemas/B001_002_Response_Get"
                  - $ref: "#/components/schemas/B001_002_Response_Delete"
                  - $ref: "#/components/schemas/B003_001_Response_Get"
                  - $ref: "#/components/schemas/B003_002_Response_Get"
                  - $ref: "#/components/schemas/B004_001_Response_Get"
                  - $ref: "#/components/schemas/B004_001_Response_Post"
                  - $ref: "#/components/schemas/B004_001_Response_Delete"
                  - $ref: "#/components/schemas/B004_002_Response_Get"
                  - $ref: "#/components/schemas/B004_002_Response_Post"
                  - $ref: "#/components/schemas/B004_002_Response_Put"
                  - $ref: "#/components/schemas/B004_002_Response_Delete"
        "422":
          description: バリデーションエラー

components:
  schemas:
    BaseRequest:
      title: 共通リクエスト
      type: object
      properties:
        ifId:
          type: string
          description: IF-ID
        method:
          type: string
          description: HTTPメソッド
        payload:
          type: object
      required: [ifId, method, payload]

    B000_001_Request_Get:
      title: B000_001_共通機能_メニュー情報BFF_リクエスト（GET）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                administrator_flg:
                  type: boolean
                  description: 管理者フラグ
              required: [administrator_flg]

    B000_002_Request_Get:
      title: B000_002_共通機能_コード値情報BFF_リクエスト（GET）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                code_id:
                  type: string
                  description: コードID
              required: [code_id]

    B001_001_Request_Post:
      title: B001_001_認証機能_ログイン照会BFF_リクエスト（POST）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                user_id:
                  type: string
                  description: ユーザーID
                password:
                  type: string
                  description: パスワード
              required: [user_id, password]

    B001_002_Request_Get:
      title: B001_002_認証機能_トークン情報BFF_リクエスト（GET）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
    B001_002_Request_Delete:
      title: B001_002_認証機能_トークン情報BFF_リクエスト（DELETE）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object

    B003_001_Request_Get:
      title: B003_001_検索機能_楽曲情報BFF_リクエスト（GET）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                artist_name:
                  type: string
                  description: 歌手名
                tune_name:
                  type: string
                  description: 曲名

    B003_002_Request_Get:
      title: B003_002_検索機能_全楽曲情報BFF_リクエスト（GET）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                artist_id:
                  type: string
                  description: 歌手ID
              required: [artist_id]

    B004_001_Request_Get:
      title: B004_001_採点機能_楽曲予約情報BFF_リクエスト（GET）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                user_id:
                  type: string
                  description: ユーザーID
              required: [user_id]
    B004_001_Request_Post:
      title: B004_001_採点機能_楽曲予約情報BFF_リクエスト（POST）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                user_id:
                  type: string
                  description: ユーザーID
                artist_id:
                  type: string
                  description: 歌手ID
                artist_name:
                  type: string
                  description: 歌手名
                tune_id:
                  type: string
                  description: 楽曲ID
                tune_name:
                  type: string
                  description: 楽曲名
                model_type:
                  type: string
                  description: 採点機種
                score:
                  type: number
                  description: 点数
                scoring_date:
                  type: string
                  description: 採点日
              required:
                [
                  user_id,
                  artist_id,
                  artist_name,
                  tune_id,
                  tune_name,
                  model_type,
                  score,
                  scoring_date,
                ]
    B004_001_Request_Delete:
      title: B004_001_採点機能_楽曲予約情報BFF_リクエスト（DELETE）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                user_id:
                  type: string
                  description: ユーザーID
                tune_id:
                  type: string
                  description: 楽曲ID
              required: [user_id, tune_id]

    B004_002_Request_Get:
      title: B004_002_採点機能_採点履歴情報BFF_リクエスト（GET）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                user_id:
                  type: string
                  description: ユーザーID
                from_date:
                  type: string
                  description: 開始日
                to_date:
                  type: string
                  description: 終了日
              required: [user_id]
    B004_002_Request_Post:
      title: B004_002_採点機能_採点履歴情報BFF_リクエスト（POST）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                user_id:
                  type: string
                  description: ユーザーID
                artist_id:
                  type: string
                  description: 歌手ID
                artist_name:
                  type: string
                  description: 歌手名
                tune_id:
                  type: string
                  description: 楽曲ID
                tune_name:
                  type: string
                  description: 楽曲名
                model_type:
                  type: string
                  description: 採点機種
                score:
                  type: number
                  description: 点数
                scoring_date:
                  type: string
                  description: 採点日
              required:
                [
                  user_id,
                  artist_id,
                  artist_name,
                  tune_id,
                  tune_name,
                  model_type,
                  score,
                  scoring_date,
                ]
    B004_002_Request_Put:
      title: B004_002_採点機能_採点履歴情報BFF_リクエスト（PUT）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                user_id:
                  type: string
                  description: ユーザーID
                tune_id:
                  type: string
                  description: 楽曲ID
                tune_name:
                  type: string
                  description: 楽曲名
                model_type:
                  type: string
                  description: 採点機種
                score:
                  type: number
                  description: 点数
                scoring_date:
                  type: string
                  description: 採点日
                registered_model_type:
                  type: string
                  description: 登録済み採点機種
                registered_scoring_date:
                  type: string
                  description: 登録済み採点日
              required:
                [
                  user_id,
                  tune_id,
                  tune_name,
                  model_type,
                  score,
                  scoring_date,
                  registered_model_type,
                  registered_scoring_date,
                ]
    B004_002_Request_Delete:
      title: B004_002_採点機能_採点履歴情報BFF_リクエスト（DELETE）
      allOf:
        - $ref: "#/components/schemas/BaseRequest"
        - type: object
          properties:
            payload:
              type: object
              properties:
                user_id:
                  type: string
                  description: ユーザーID
                tune_id:
                  type: string
                  description: 楽曲ID
                model_type:
                  type: string
                  description: 採点機種
                scoring_date:
                  type: string
                  description: 採点日
              required: [user_id, tune_id, model_type, scoring_date]

    BaseResponse:
      title: 共通レスポンス
      type: object
      properties:
        success_flg:
          type: boolean
          description: 正常終了フラグ
        code:
          type: string
          description: 結果コード
        message:
          type: string
          description: 結果メッセージ
      required: [success_flg, code]

    B000_001_Response_Get:
      title: B000_001_共通機能_メニュー情報BFF_レスポンス（GET）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  sort:
                    type: number
                    description: ソート順
                  label:
                    type: string
                    description: ラベル
                  icon:
                    type: string
                    description: アイコン
                  content:
                    type: string
                    description: 内容
                  administrator_flg:
                    type: boolean
                    description: 管理者フラグ

    B000_002_Response_Get:
      title: B000_002_共通機能_コード値情報BFF_レスポンス（GET）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  code_value:
                    type: string
                    description: コード値
                  code_name:
                    type: string
                    description: コード名

    B001_001_Response_Post:
      title: B001_001_認証機能_ログイン照会BFF_レスポンス（POST）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  user_id:
                    type: string
                    description: ユーザーID
                  user_name:
                    type: string
                    description: ユーザー名
                  administrator_flg:
                    type: boolean
                    description: 管理者フラグ

    B001_002_Response_Get:
      title: B001_002_認証機能_トークン情報BFF_レスポンス（GET）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  user_id:
                    type: string
                    description: ユーザーID
                  user_name:
                    type: string
                    description: ユーザー名
                  administrator_flg:
                    type: boolean
                    description: 管理者フラグ
    B001_002_Response_Delete:
      title: B001_002_認証機能_トークン情報BFF_レスポンス（DELETE）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス

    B003_001_Response_Get:
      title: B003_001_検索機能_楽曲情報BFF_レスポンス（GET）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  artist_info:
                    type: array
                    description: 歌手情報
                    items:
                      type: object
                      properties:
                        artist_id:
                          type: string
                          description: 歌手ID
                        artist_name:
                          type: string
                          description: 歌手名
                        popularity:
                          type: number
                          description: 人気度
                        follower:
                          type: number
                          description: フォロワー数
                        genre:
                          type: array
                          description: ジャンル
                          items:
                            type: string
                        image:
                          type: string
                          description: 画像
                        external_url:
                          type: string
                          description: 外部URL
                  tune_info:
                    type: array
                    description: 楽曲情報
                    items:
                      type: object
                      properties:
                        artist_id:
                          type: string
                          description: 歌手ID
                        artist_name:
                          type: string
                          description: 歌手名
                        tune_id:
                          type: string
                          description: 楽曲ID
                        tune_name:
                          type: string
                          description: 楽曲名
                        popularity:
                          type: number
                          description: 人気度
                        release_date:
                          type: string
                          description: リリース日
                        image:
                          type: string
                          description: 画像
                        external_url:
                          type: string
                          description: 外部URL

    B003_002_Response_Get:
      title: B003_002_検索機能_全楽曲情報BFF_レスポンス（GET）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  artist_id:
                    type: string
                    description: 歌手ID
                  artist_name:
                    type: string
                    description: 歌手名
                  tune_id:
                    type: string
                    description: 楽曲ID
                  tune_name:
                    type: string
                    description: 楽曲名
                  release_date:
                    type: string
                    description: リリース日
                  image:
                    type: string
                    description: 画像
                  external_url:
                    type: string
                    description: 外部URL

    B004_001_Response_Get:
      title: B004_001_採点機能_楽曲予約情報BFF_レスポンス（GET）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  user_id:
                    type: string
                    description: ユーザーID
                  artist_id:
                    type: string
                    description: 歌手ID
                  artist_name:
                    type: string
                    description: 歌手名
                  tune_id:
                    type: string
                    description: 楽曲ID
                  tune_name:
                    type: string
                    description: 楽曲名
                  model_type:
                    type: string
                    description: 採点機種
                  score:
                    type: number
                    description: 点数
                  scoring_date:
                    type: string
                    description: 採点日
    B004_001_Response_Post:
      title: B004_001_採点機能_楽曲予約情報BFF_レスポンス（POST）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス
    B004_001_Response_Delete:
      title: B004_001_採点機能_楽曲予約情報BFF_レスポンス（DELETE）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス

    B004_002_BaseResponse_Get:
      title: B004_002_採点機能_採点履歴情報BFF_共通レスポンス（GET）
      type: object
      properties:
        user_id:
          type: string
          description: ユーザーID
        artist_id:
          type: string
          description: 歌手ID
        artist_name:
          type: string
          description: 歌手名
        tune_id:
          type: string
          description: 楽曲ID
        tune_name:
          type: string
          description: 楽曲名
        score:
          type: number
          description: 点数
        scoring_date:
          type: string
          description: 採点日
    B004_002_Response_Get:
      title: B004_002_採点機能_採点履歴情報BFF_レスポンス（GET）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  joysound:
                    type: array
                    items:
                      $ref: "#/components/schemas/B004_002_BaseResponse_Get"
                  joysound_ai:
                    type: array
                    items:
                      $ref: "#/components/schemas/B004_002_BaseResponse_Get"
                  dam:
                    type: array
                    items:
                      $ref: "#/components/schemas/B004_002_BaseResponse_Get"
                  dam_ai:
                    type: array
                    items:
                      $ref: "#/components/schemas/B004_002_BaseResponse_Get"
    B004_002_Response_Post:
      title: B004_002_採点機能_採点履歴情報BFF_レスポンス（POST）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス
    B004_002_Response_Put:
      title: B004_002_採点機能_採点履歴情報BFF_レスポンス（PUT）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス
    B004_002_Response_Delete:
      title: B004_002_採点機能_採点履歴情報BFF_レスポンス（DELETE）
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            response_info:
              type: array
              items:
                type: object
                properties:
                  status:
                    type: string
                    description: ステータス
